const customers = [
  'Gwendoline', 'Sigmund', 'Zed', 'Bartholomew',
  'Nestor', 'Remington', 'Harry', 'Gertrude',
  'Mildred', 'Petunia', 'Sven', 'Clementine',
  'Harold', 'Buster', 'Joe', 'Marjorie', 'Randolph',
  'Gilbert', 'Gloria', 'Lola', 'Lionel', 'Stu',
  'Betsy', 'Todd', 'Dirk', 'Bertha', 'Olga', 'Agatha',
  'Agnes', 'Gus', 'Ned', 'Jed', 'Lucretia', 'Gabby',
  'Tabatha', 'Norm', 'Bjorn', 'Carl', 'Phoebe',
];

const items = [
  'a chocolate sundae',
  'a rocky road cone',
  'a vanilla scoop',
  'a neapolitan bowl',
  'a fudge bowl',
  'a coffee',
  'a kids size amount of ice cream',
  'two flavors of something',
  'a special sundae',
  'a seasonal flavor',
  'four low fat cones',
  'an affogato',
  'some sorbet',
  'a deluxe serving',
  'some soft serve which is not available',
  'more ice cream',
  'every flavor possible',
  'two fudge bowls nested inside each other',
  'a double vanilla crunch',
  'some fruit',
  'to sample the chocolate',
  'the gluten free thing',
  'the weird floral flavor',
  'some quantity of almond topping',
  'napkins',
  'two scoops of lemon flavor',
  'orange sherbert',
  'double chocolate super cake',
  'the quadruple chocolate nightmare',
  'a frosty treat',
  'the italian chocolate variety',
  'grapefruits',
  'just a bunch of cones with no ice cream',
  'lemon sorbet with a little bit of chocolate',
  'the expensive kind',
  'a silly kids flavor',
  'diet ice cream',
  'two sundaes extra fudge',
  'more napkins',
  'no vegetables',
  'cups for water',
  'two scoops of strawberry ice cream',
  'a vanilla cup with berries',
  'an extra huge serving of peanut butter',
  'a frosty surprise',
  'a double frosty surprise',
  'a fruity frosty cone',
  'something flavored like bubble gum',
  'a french vanilla bucket',
  'a triple frosty crunch bucket',
  'just some ice',
  'a milk shake',
  'a mork shake',
  'milks',
  'an extra cold ice cream',
  'blueberry sorbet',
  'one chocolate one vanilla',
  'a peanut butter swirl',
  'some nuts',
  'to be rewarded for their patience',
];

const responses = [
  'son',
  'pardner',
  'bucko',
  'pal',
  'neighborino',
  'buddy',
  'you',
  'you hip cat',
  'bro',
  'bromigo',
  'duder',
  'young man',
  'fella',
  'young one',
  'bud',
  'bruh',
  'bruu',
  'boy',
  'young sir',
  'my good man',
  'child',
  'you beastly man',
  'horsemaster',
];

const levelThresholds = [
  25,
  50,
  100,
  200,
  500,
  1000,
  2000,
  5000,
  10000,
  20000,
  50000,
  100000,
  1000000,
];

export default {
  customers,
  items,
  responses,
  levelThresholds,
};
